api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    resource_class_directories:
        - '%kernel.project_dir%/src/ApiResource'
#    default_version: 1.0.0
#    default_format: jsonld
    default_timezone: UTC-3
    default_locale: es
    debug: false
    enable_profiler: true
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    enable_nelmio_api_doc: true
