security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            # Session-based auth (default). For API JSON login, enable json_login below.
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                # success & failure handlers are default (204 + error JSON in modern versions)
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/api/me, roles: ROLE_USER }
        # Allow anonymous to login
        - { path: ^/login$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
