<?php
$output = [
    ['smalley_Likes_Control', 'Me gusta el control', 'd'],
    ['smalley_Enthusiastic', 'Entusiasta', 'i'],
    ['smalley_Sensitive', 'Sensible', 's'],
    ['smalley_Reserved', 'Reservado', 'c'],
    ['smalley_Firm', 'Firme', 'd'],
    ['smalley_Energetic', 'Enérgico', 'i'],
    ['smalley_Non_Demanding', 'No exigente', 's'],
    ['smalley_Practical', 'Práctico', 'c'],
    ['smalley_Likes_Challenge', 'Me gusta el desafío', 'd'],
    ['smalley_Promoter', 'Promotor', 'i'],
    ['smalley_Enjoys_Routine', 'Disfruta las rutinas', 's'],
    ['smalley_Factual', 'Hechos', 'c'],
    ['smalley_Problem_Solver', 'Solucionador de problemas', 'd'],
    ['smalley_Mixes_Easily', 'Se relaciona fácilmente', 'i'],
    ['smalley_Relational', 'Relacional', 's'],
    ['smalley_Perfectionistic', 'Perfeccionista', 'c'],
    ['smalley_Bold', 'Audaz', 'd'],
    ['smalley_Fun_Loving', 'Ama la diversión', 'i'],
    ['smalley_Thoughtful', 'Pensativo', 's'],
    ['smalley_Detailed', 'Detallista', 'c'],
    ['smalley_Goal_Driven', 'Impulsado por objetivos', 'd'],
    ['smalley_Optimistic', 'Optimista', 'i'],
    ['smalley_Patient', 'Paciente', 's'],
    ['smalley_Inquisitive', 'Inquisitivo', 'c'],
    ['smalley_Strong_Willed', 'Voluntad Fuerte', 'd'],
    ['smalley_Motivator', 'Motivador', 'i'],
    ['smalley_Good_Listener', 'Buen oyente', 's'],
    ['smalley_Accurate', 'Preciso', 'c'],
    ['smalley_Takes_Charge', 'Se hace cargo', 'd'],
    ['smalley_Very_Verbal', 'Muy verbal', 'i'],
    ['smalley_Loyal', 'Leal', 's'],
    ['smalley_Predictable', 'Predecible', 'c'],
    ['smalley_Determined', 'Determinado', 'd'],
    ['smalley_Popular', 'Popular', 'i'],
    ['smalley_Dislikes_Change', 'No le gusta el cambio', 's'],
    ['smalley_Orderly', 'Ordenado', 'c'],
    ['smalley_Competitive', 'Competitivo', 'd'],
    ['smalley_Group_Oriented', 'Orientado a los grupos', 'i'],
    ['smalley_Sympathetic', 'Simpático', 's'],
    ['smalley_Analytical', 'Analítico', 'c'],
    ['smalley_Purposeful', 'Determinado', 'd'],
    ['smalley_Inspirational', 'Inspiracional', 'i'],
    ['smalley_Nurturing', 'Fomenta', 's'],
    ['smalley_Precise', 'Preciso', 'c'],
    ['smalley_Action_Oriented', 'Orientado a la acción', 'd'],
    ['smalley_Likes_Change', 'Me gusta el cambio', 'i'],
    ['smalley_Peace_Maker', 'Pacificador', 's'],
    ['smalley_Scheduled', 'Planificador', 'c']
];